extern void Initialization (int *Geno, int *PreGeno,
                            struct IND *Individual, int *Translation,
                            int *NumAlleles, int *Z, int *Z1, float *Epsilon,
                            float *SumEpsilon,
                            float *Fst,float *PSum, float *Q, float *QSum,
                            float *FstSum,
                            int *AncestDist, float *UsePopProbs, float *Alpha,
                            float *sumAlpha, float *sumR, float *varR,
                            float *sumlikes, float *sumsqlikes,
                            int *savefreq, float *R, float *lambda, float *sumlambda,
                            float *Phase, int *Recessive, float *LocPrior,
                            float *sumLocPrior, int LocPriorLen,
                            float *sumIndLikes, float *indlike_norm, CLDict *clDict);
