#define QSIZE NUMINDS*MAXPOPS
#define PSIZE NUMLOCI*MAXPOPS*MAXALLELES
#define ZSIZE NUMINDS*LINES*NUMLOCI
#define GENOSIZE LINES*NUMLOCI*NUMINDS
#define MAXRANDOM 64
#define RANDSIZE NUMINDS*NUMLOCI*MAXRANDOM

